<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SecondUserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //manager
        DB::table('users')->insert([
            'id' => 3,
            'name' => 'eManager',
            'phoneNumber' => 12312312312,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => NULL,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 2,
            'schoolId' => 1,
            'gradeId' => NULL,
            'lessonId' => NULL,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 123123123123123123,
            'familyAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'residenceAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'fatherName' => NULL,
            'fatherPhone' => NULL,
            'fatherJob' => NULL,
            'introduce' => NULL,
            'birthday' => NULL,
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => NULL,
            'status' => '在办公室',
            'subjectName' => NULL,
            'children' => NULL,
        ]);

        //banzhuren
        DB::table('users')->insert([
            'id' => 4,
            'name' => 'banzhu1',
            'phoneNumber' => 23423423423,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => NULL,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 7,
            'schoolId' => 1,
            'gradeId' => 1,
            'lessonId' => 1,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 234234234234234234,
            'familyAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'residenceAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'fatherName' => NULL,
            'fatherPhone' => NULL,
            'fatherJob' => NULL,
            'introduce' => NULL,
            'birthday' => NULL,
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => '[0, 1]',
            'status' => '在办公室',
            'subjectName' => NULL,
            'children' => NULL,
        ]);

        //teacher
        DB::table('users')->insert([
            'id' => 5,
            'name' => 'teacher1',
            'phoneNumber' => 34534534534,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => NULL,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 3,
            'schoolId' => 1,
            'gradeId' => NULL,
            'lessonId' => NULL,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 345345345345345345,
            'familyAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'residenceAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'fatherName' => NULL,
            'fatherPhone' => NULL,
            'fatherJob' => NULL,
            'introduce' => NULL,
            'birthday' => NULL,
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => '[0]',
            'status' => '在办公室',
            'subjectName' => NULL,
            'children' => NULL,
        ]);

        //student
        DB::table('users')->insert([
            'id' => 6,
            'name' => 'student1',
            'phoneNumber' => 56756756756,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => 567567567,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 5,
            'schoolId' => 1,
            'gradeId' => 1,
            'lessonId' => 1,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 567567567567567567,
            'familyAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'residenceAddress' => NULL,
            'fatherName' => 'parent1',
            'fatherPhone' => '45645645645',
            'fatherJob' => 'father',
            'introduce' => 'introduce of Student 1',
            'birthday' => '2010-02-02 16:00:00',
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => '[0, 1]',
            'status' => '上课中',
            'subjectName' => NULL,
            'children' => NULL,
        ]);

        //parent
        DB::table('users')->insert([
            'id' => 7,
            'name' => 'parent1',
            'phoneNumber' => 45645645645,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => NULL,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 4,
            'schoolId' => 1,
            'gradeId' => NULL,
            'lessonId' => NULL,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 456456456456456456,
            'familyAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'residenceAddress' => '{"city": "110100", "detail": "123123123", "region": "110101", "province": "110000"}',
            'fatherName' => NULL,
            'fatherPhone' => NULL,
            'fatherJob' => NULL,
            'introduce' => NULL,
            'birthday' => NULL,
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => '[0]',
            'status' => '上课中',
            'subjectName' => NULL,
            'children' => '[6]',
        ]);

        //employee
        DB::table('users')->insert([
            'id' => 8,
            'name' => 'em1',
            'phoneNumber' => 89089089089,
            'password' => '$2y$10$uFsdSAUKC.X3KPUA4Rf5feSejyZPKuc/q0bsEAq8m3Dh4FZnWO.gq',
            'imei' => NULL,
            'avatar' => '/',
            'remember_token' => NULL,
            'created_at' => '2021-06-09 04:18:50',
            'updated_at' => '2021-06-09 04:18:50',
            'roleId' => 6,
            'schoolId' => 1,
            'gradeId' => NULL,
            'lessonId' => NULL,
            'gender' => 'M',
            'nation' => '汉族',
            'cardNum' => 890890890890890890,
            'familyAddress' => NULL,
            'residenceAddress' => NULL,
            'fatherName' => NULL,
            'fatherPhone' => NULL,
            'fatherJob' => NULL,
            'introduce' => NULL,
            'birthday' => NULL,
            'statusFrom' => NULL,
            'statusTo' => NULL,
            'schoolItem' => NULL,
            'classItem' => NULL,
            'wechat' => NULL,
            'qq' => NULL,
            'studentId' => NULL,
            'groupArr' => NULL,
            'status' => '在办公室',
            'subjectName' => NULL,
            'children' => NULL,
        ]);
    }
}
