// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

//toggledrawer.js
export const TOGGLE_MINI_DRAWER = 'TOGGLE_MINI_DRAWER'
export const TURN_DRAWER = 'TURN_DRAWER'


//schooltree.js
export const STORE_SCHOOL_TREE = 'STORE_SCHOOL_TREE'
export const STORE_SCHOOL_DATA = 'STORE_SCHOOL_DATA'
export const STORE_MEMBER_DATA = 'STORE_MEMBER_DATA'
export const STORE_CHOOSEABLE_SCHOOL_TREE = 'STORE_CHOOSEABLE_SCHOOL_TREE'


// lang.js
export const SET_LOCALE = 'SET_LOCALE'

//questionnaire.js
export const STORE_SINGLE_DATA = 'STORE_SINGLE_DATA'
export const STORE_MULTI_DATA = 'STORE_MULTI_DATA'
export const STORE_QA_DATA = 'STORE_QA_DATA'
export const STORE_STAT_DATA = 'STORE_STAT_DATA'
export const STORE_SCORING_DATA = 'STORE_SCORING_DATA'
export const STORE_POST_NEW = 'STORE_POST_NEW'
export const STORE_POST_DETAIL = 'STORE_POST_DETAIL'

//chat
export const STORE_USERS = 'STORE_USERS'
export const STORE_CONTACTLIST = 'STORE_CONTACTLIST'
export const STORE_GROUPLIST = 'STORE_GROUPLIST'
export const STORE_TOTALNEWMESSAGECOUNT = 'STORE_TOTALNEWMESSAGECOUNT'
export const STORE_ADDRESSEDUSERS = 'STORE_ADDRESSEDUSERS'

//mo
export const IS_SCHOOLSPACE = 'IS_SCHOOLSPACE'
export const SELECT_SCHOOL_ITEM = 'SELECT_SCHOOL_ITEM'
export const SCHOOL_ITEM_GROUP = 'SCHOOL_ITEM_GROUP'
export const CLASS_ITEM_GROUP = 'CLASS_ITEM_GROUP'
export const SCHOOL_ITEM_GROUP_FOR_DIA = 'SCHOOL_ITEM_GROUP_FOR_DIA'
export const CLASS_ITEM_GROUP_FOR_DIA = 'CLASS_ITEM_GROUP_FOR_DIA'