import './axios'
import './fontawesome'
import './qrcode'
import './datetimepicker'
import './readmore'
import './imageviewer'
import './videoview'
import './infinite'
import './vchatscroll'
import './mobiledetect'
import './fragment'
import './quickmenu'

import 'bootstrap'
